# from https://github.com/Parallels/atlassian-restrict-branch-model/blob/master/.travis.yml
sudo: false

language: java

before_install:
- wget https://marketplace.atlassian.com/download/plugins/atlassian-plugin-sdk-tgz
- mkdir opt
- tar -xvzf *plugin-sdk* -C opt
- mv opt/*plugin-sdk* opt/atlassian-plugin-sdk
- chmod a+x opt/atlassian-plugin-sdk/bin/*
- chmod a+x opt/atlassian-plugin-sdk/apache-maven-*/bin/*
- export PATH=opt/atlassian-plugin-sdk/bin:opt/atlassian-plugin-sdk/apache-maven-*/bin:$PATH
- atlas-version
install:
- atlas-mvn install
script:
- atlas-mvn package
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "ajNbIxmkYSEt2cDOng8qKMYdJkDaud3HUTHc/hPNxhbqNvhKahHajWQolaj6TvRMLeprN07j4vH/DiafNnQd5GYbhOM+A4BDF4RiTfXlP4t65SKeoAcXIk2ed1O3Xj9FaOBtGwIevIzx45cxFgC6gKuYpT2xqj1X0w+x6IqaWuIpuIhkh9LgfeyuYo0fES22FFQuNBtfB81MKm6AKmEZdd+0F63oD2qjsIDU2bGOcf2gSgM6x4Erv7QH+uFkRc+ki/2/1YsNnM7sOkOMk/S1UA/7cSMp60x/B28NoIrWHzShLAeiPXolKb52vz1szN5pUKGs8p0nfAkYd+3ml9cNryyfxfW6p08wRqAH3pXzo0V0JLiioIELwBW4AxsGvSGi9Dy4emeh8O2X5e3mpAKPkXfD67xh8IWwkceljw/VEQ3KFX1nOVIJn/ZUWrzs7FsvJj4yez/pSz08Y6423whEgBDfcDqADxdZpUV7vgrPLbjimEfalUFvXTb/fukGswuSAUVbAvlUiwmJnKOS0T560luZxjj/ke+QxHQyA5d5X3QsEv00qhYBHZ4VXW1hhnpk7XNWa4cyJKQIKWm0snqME37sS6/okmlk5aDIIjkU2m1MSXW4mYmp5Vrodc+t9+dC+MbVOStN4LGup9j7QsyuyVzfpNsKohgC2w6q7EATDyc="
  file:
    - target/*.jar
  file_glob: true
  on:
    branch: master
